
bricks_base_env_config:
  table:
    full_size: [0.8, 0.8, 0.05]
    friction: [1.0, 0.005, 0.0001]
    offset: [0, 0, 0.8]

single_arm_env_config:
  env_configuration: default
  initialization_noise: default

  robots: Panda
  gripper_types: default

  use_camera_obs: True

  has_renderer: False
  has_offscreen_renderer: True
  render_camera: frontview
  render_collision_mesh: False
  render_visual_mesh: True
  render_gpu_device_id: -1
  control_freq: 20
  horizon: 1000
  ignore_done: False
  hard_reset: True

  camera_names: agentview
  camera_heights: 256
  camera_widths: 256
  camera_depths: False
  # camera_segmentations=None,  # {None, instance, class, element}
  renderer: mujoco
